name: proclinic_models
description: extracted proclinic models library.
version: 0.0.1
repository: https://github.com/pheonixeye/proclinic_models.git

environment:
  sdk: ^3.2.0

dependencies:
  equatable: ^2.0.5
  mongo_dart:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
